### ISSUE TITLE
неверно (не там) определены контрагенты

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#10]
1 Договор.docx.json

![photo_2019-10-16_20-38-14](https://user-images.githubusercontent.com/7677437/66919959-f3d12580-f054-11e9-9b63-2b86c8c7c73c.jpg)

@IvanKrivosh

**Comment by compartia** [comment]
вероятнее всего пофиксится при переключении на более свежую версию document-parser, именно в нем определяются headlines

**Comment by SergeyShalaevsky** [comment]
я бы сказал пофиксится или нет, если бы смог найти этот 1 Договор.docx

**Comment by IvanKrivosh** [comment]
По поводу документа я напарил, это я локально с ним работал. Елисей закачал:
19.10.06
1.1. Договор пожертвования

**Comment by SergeyShalaevsky** [comment]
пофиксится

**Comment by compartia** [comment]
<img width="990" alt="Capture d’écran 2019-11-30 à 22 14 40" src="https://user-images.githubusercontent.com/7677437/69901613-0910d200-13bf-11ea-9cf2-dd096b7a6c3d.png">

**Comment by compartia** [comment]
#77
