### ISSUE TITLE
Необычный номер договора не найден

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#131]
<img width="968" alt="Capture d’écran 2020-02-28 à 16 14 15" src="https://user-images.githubusercontent.com/7677437/75522707-922eb800-5a45-11ea-8f9f-e072ecaa202a.png">

```
текст документа
Договор 259/ХХ/859 об оказании услуг

г. Санкт-Петербург                                             «02» Марта 2017 Датагод.
Общество с ограниченной ответственностью Форма собственности контрагента«ШтормНаименование контрагента» (ООО «Шторм»)Краткое наименование контрагента, именуемое в дальнейшем «ИсполнительПсевдоним контрагента», в лице Генерального директора ХХХ ХХХ ХХХ, действующего на основании Устава, с одной стороны, и Общество с ограниченной ответственно

```

see also #130 #69 #71 #93

**Comment by compartia** [comment]
олсо в этом примере номер режется последним слэшем 
```ДОГОВОР НА ОКАЗАНИЕ УСЛУГ №Номер  13/10542/Р.```

**Comment by compartia** [comment]
upd

**Comment by compartia** [comment]
вообще, в этом датасете все номера договоров опрелелены дефективно
(см картину)
<img width="1561" alt="Capture d’écran 2020-02-28 à 18 01 23" src="https://user-images.githubusercontent.com/7677437/75538950-7252c080-5a54-11ea-8df6-03dcd5be6974.png">

**Comment by LitJane** [comment]
ДОГОВОР № 100мн/16 Генерального подряда определился как 100

ДОГОВОР НА ОКАЗАНИЕ УСЛУГ № 13/00042/Р. определился как 13/0004

Договор 259/ХХ/859 об оказании услуг определился как ______

Договор № КБ 019753 определился как КБ 0197

ДОГОВОР КУПЛИ-ПРОДАЖИ НЕДВИЖИМОГО ИМУЩЕСТВА №Номер 548/9587/НК  определился как 548/9587

**Comment by compartia** [comment]
@thingumajig беда беда https://github.com/nemoware/analyser/runs/479927009

**Comment by thingumajig** [comment]
@compartia  всё-таки что-то надо сделать с лишними имплантированными пробелами

**Comment by thingumajig** [comment]
@compartia А, ещё и тест неправильный, не использует capture group

**Comment by thingumajig** [comment]
@compartia пофиксил тест, но внедрённые пробелы....

**Comment by thingumajig** [comment]
можно закрывать, не самая суперважная хрень

**Comment by compartia** [comment]
Находится номер дока после слова "доверенности"
это не гуд.
"в лице Жерара Депардье , действующего на основании доверенности № АБРАКАДАБРА123-БИС/Й от 01-01-2021 "

**Comment by thingumajig** [comment]
есть стандартный способ добавить запрещённые префиксы
![image](https://user-images.githubusercontent.com/8703531/80491844-eaae0300-896b-11ea-8f2d-9c45371a3ace.png)
В какой нынче ветке править?

**Comment by compartia** [comment]
> В какой нынче ветке править?

я всегда стандартно предлагаю схему -- отщипывать от `dev` "хотфикс-номербага", на ней ухудшать мир к лучшему, делать пуллреквест с комментом `closes #номербага`

**Comment by compartia** [comment]
- [ ]  номер договора не может быть просто "номер"
- [ ]  номер договора не может быть просто "г"

<img width="328" alt="Capture d’écran 2020-06-11 à 10 58 36" src="https://user-images.githubusercontent.com/7677437/84340997-a5b8f580-abd4-11ea-8703-f85cd0b08b8e.png">
<img width="74" alt="Capture d’écran 2020-06-11 à 10 54 15" src="https://user-images.githubusercontent.com/7677437/84341002-a94c7c80-abd4-11ea-8c21-cdc2b8091b73.png">
<img width="820" alt="Capture d’écran 2020-06-11 à 10 52 35" src="https://user-images.githubusercontent.com/7677437/84341003-a9e51300-abd4-11ea-9fb9-f2573ceee724.png">

@thingumajig 
возможно, нужно подправить `document_number_valid_c`
please fix on https://github.com/nemoware/analyser/tree/hotfix-131-exlude-powerofattorney branch
