### ISSUE TITLE
даты: Неверно связан Договор с уставом

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#132]
Конечно, нужно уточнить у @LitJane , но договор не должен быть моложе устава

Сет:
`Примеры документов/Документы для апробации MVP(28.02.2020)`
Картина:
<img width="588" alt="Capture d’écran 2020-02-28 à 18 12 10" src="https://user-images.githubusercontent.com/7677437/75539982-243ebc80-5a56-11ea-95b4-57f06a2ded51.png">

**Comment by SergeyShalaevsky** [comment]
наоборот устав должен быть принят раньше договора

**Comment by compartia** [comment]
> наоборот устав должен быть принят раньше договора

да, я опчатался, ту как раз устав позже дога

**Comment by SergeyShalaevsky** [comment]
2016 год раньше 2017 :)

**Comment by compartia** [comment]
ах гооооооод ты еще учитываешь
оооокей,
простите за беспокойство

**Comment by compartia** [comment]
зато я бдительный
