### ISSUE TITLE
Некорректно извлекается номер договора, если в нем содержатся буквы

### ISSUE THREAD

**Issue by LitJane** [nemoware/analyser#133]
Номер договора "обрезается" как только в поле зрения анализатора попадает буква.

![image](https://user-images.githubusercontent.com/55797683/75542485-fa26d380-5a30-11ea-9f40-d98808292bc6.png)
![image](https://user-images.githubusercontent.com/55797683/75542500-027f0e80-5a31-11ea-9352-8beb918fe40e.png)

_хэштегартемкосячит_

**Comment by thingumajig** [comment]
#131

**Comment by compartia** [comment]
closing as dup
