### ISSUE TITLE
Можно ли (нужно ли) дату вступления договора в силу считать датой договора?

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#177]
Скриншот:
<img width="619" alt="Capture d’écran 2020-06-07 à 11 31 22" src="https://user-images.githubusercontent.com/7677437/83985435-d5b19000-a96b-11ea-819c-c74c8cead44e.png">

Или же та дата, которая указана в шапке (дата подписания) важнее?

**Comment by LitJane** [comment]
Мы сверяем договор с другими документами  (протоколом и уставом) по дате подписания.
