### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#185]
если отредактировать атрибуты лишь одного документа, то пере-анализируются все документы из задания на аудит.
@SergeyShalaevsky , ты не помнишь, почему мы так сделали?
В случае, когда документов много, повторный анализ занимает неоправданно много времени.

**Comment by SergeyShalaevsky** [comment]
такого быть не должно, на анализ попадают только доки с определенным стейтом.

**Comment by compartia** [comment]
> такого быть не должно, на анализ попадают только доки с определенным стейтом.

вот потому и баг завожу, что такого быть не должно ;-)

**Comment by SergeyShalaevsky** [comment]
Такое поведение, актуально только для старых аудитов. Дело в том, что если версия анализатора изменилась по сравнению с версией, с которой документы были анализированы в предыдущий раз, то они пере-анализируются заново. На той же самой версии пере-анализируются только измененные доки.
