### ISSUE TITLE
Ошибка анализа протоколов

### ISSUE THREAD

**Issue by vanyasav** [nemoware/analyser#225]
Nemoware Analyser v2.0.2

- Наименование ДО в протоколах пропадает после анализа

- Орган управления и дата не обнаружены (в старых версиях анализатора они есть)

После загрузки файлов:
![image](https://user-images.githubusercontent.com/37312123/92745830-5e850100-f38b-11ea-83e7-3c085bb22fdc.png)

После анализа:
![image](https://user-images.githubusercontent.com/37312123/92745957-7c526600-f38b-11ea-9cf9-7b60b3f9f678.png)

**Comment by vanyasav** [comment]
Аналогично для уставов

**Comment by compartia** [comment]
fixed with Release v2.0.4
