### ISSUE TITLE
v 2.0.4 не анализируются протоколы и договоры

### ISSUE THREAD

**Issue by vanyasav** [nemoware/analyser#234]
![image](https://user-images.githubusercontent.com/37312123/94904394-eef2c500-04a3-11eb-9108-1e6caa7107e7.png)

![image](https://user-images.githubusercontent.com/37312123/94904489-1184de00-04a4-11eb-892f-b8af9beec772.png)

**Comment by compartia** [comment]
<img width="598" alt="Capture d’écran 2020-10-04 à 10 57 28" src="https://user-images.githubusercontent.com/7677437/95005914-7a995c80-0630-11eb-817b-f048d1da0eca.png">

**Comment by compartia** [comment]
fixed in release v2.0.5
