### ISSUE TITLE
Атрибут "Валюта" определяется вне родительского атрибута "Сумма договора"

### ISSUE THREAD

**Issue by vanyasav** [nemoware/analyser#237]
![image](https://user-images.githubusercontent.com/37312123/95196409-b2470680-07e0-11eb-8747-fb6b3fa28b1a.png)

Если удалить валюту, разметить заново ее невозможно, т.к. атрибут находится вне родительского => нужно размечать сумму договора заново.

**Comment by compartia** [comment]
#242

**Comment by compartia** [comment]
#143
