### ISSUE TITLE
AllMembers duplicated key

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/analyser#238]
поймал такое на тесте v2.0.5 
окт 07 12:38:24 dc2 bash[15008]: RuntimeError: AllMembers duplicated key
окт 07 12:38:24 dc2 bash[15008]: ERROR:gpn:cant process document 5e6101680cf5aa0cfe37d149
окт 07 12:38:24 dc2 bash[15008]: Traceback (most recent call last):
окт 07 12:38:24 dc2 bash[15008]:   File "/srv/gpn_audit/analyser/analyser/runner.py", line 75, in process
окт 07 12:38:24 dc2 bash[15008]:     save_analysis(db_document, legal_doc, state=DocumentState.Done.value)
окт 07 12:38:24 dc2 bash[15008]:   File "/srv/gpn_audit/analyser/analyser/runner.py", line 190, in save_analysis
окт 07 12:38:24 dc2 bash[15008]:     analyse_json_obj = doc.to_json_obj()
окт 07 12:38:24 dc2 bash[15008]:   File "/srv/gpn_audit/analyser/analyser/legal_docs.py", line 203, in to_json_obj
окт 07 12:38:24 dc2 bash[15008]:     j = DocumentJson(self)
окт 07 12:38:24 dc2 bash[15008]:   File "/srv/gpn_audit/analyser/analyser/legal_docs.py", line 394, in __init__
окт 07 12:38:24 dc2 bash[15008]:     self.attributes = self.__tags_to_attributes_dict(doc.get_tags())
окт 07 12:38:24 dc2 bash[15008]:   File "/srv/gpn_audit/analyser/analyser/legal_docs.py", line 413, in __tags_to_attributes_dict
окт 07 12:38:24 dc2 bash[15008]:     raise RuntimeError(key + ' duplicated key')
окт 07 12:38:24 dc2 bash[15008]: RuntimeError: AllMembers duplicated key

**Comment by compartia** [comment]
#242

**Comment by compartia** [comment]
скорее всего пофикшено в 2.3.+
