### ISSUE TITLE
Валюта определяется вне суммы договора

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/analyser#277]
При разметке суммы договора анализатор предлагает разметить родительский атрибут "Сумма договора", а затем собственно сумму и единицу измерения (валюта). 
Но сам анализатор размечает сумму договора и валюту отдельно (валюта не в родительском атрибуте).
![image](https://user-images.githubusercontent.com/72862437/100742651-2fab8380-33ec-11eb-90f4-4b657d67f80b.png)

**Comment by compartia** [comment]
duplicates #237
