### ISSUE TITLE
Фильтрация документов: выставлять особый статус докам, которые не прошли фильтр

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#48]
- [ ] проблема в том, что на UI они будут видны в статусе "вот-вот проанализируем" вечно.

<img width="1249" alt="Capture d’écran 2019-12-07 à 15 07 18" src="https://user-images.githubusercontent.com/7677437/70370953-b7f56680-1907-11ea-90b6-075ca1d3a8c7.png">

**Comment by compartia** [comment]
примечание: доки, в которых контрагент не обнаружен, потенциально входят в аудит

**Comment by compartia** [comment]
- [ ] непосредственно перед тем, как док взят в анализ, ему тоже нужно ставить некий стэйт. 
- [ ] нужно отмечать доки, которые не смогли обработаться
- [ ] избегать ситуации, когда один док берется на анализ вечно и вечно ломается -- видимо, записывать счетчик retries

**Comment by SergeyShalaevsky** [comment]
> примечание: доки, в которых контрагент не обнаружен, потенциально входят в аудит

да, но в примере не обнаружена ДО, поэтому он и не попал в аудит


> * непосредственно перед тем, как док взят в анализ, ему тоже нужно ставить некий стэйт.

не вижу в этом какой-то необходимости

**Comment by compartia** [comment]
> не вижу в этом какой-то необходимости

в теории, для ускорения всего, мы можем иметь два(+) сервера, смотрящих в одну базу.
Если первый сервер взял док на анализ, второй должен его игнорить

**Comment by compartia** [comment]
олсо. Я провел тест на большой кучке доков, и, кажется, там курсор монго отваливается часа через ~2. Возможно, после каждого дока нужно перекверивать список доков.

**Comment by compartia** [comment]
> > примечание: доки, в которых контрагент не обнаружен, потенциально входят в аудит
> 
> да, но в примере не обнаружена ДО, поэтому он и не попал в аудит

если в договоре обнаружены обе организации и ни одна из них не та, по которой ведется аудит, то договор в игнор.
если обнаружена только одна, то договор стоит анализировать (ИМХО)

**Comment by SergeyShalaevsky** [comment]
новые состояния дока(с запасом):
0 - обработан парсером
5 - анализ фаза 1 пройдена
10 - взят на 2 фазу анализа
15 - вторая фаза анализа пройдена
11 - ошибка 2 фазы анализа
