### ISSUE TITLE
Неправильно показано нарушение

### ISSUE THREAD

**Issue by LitJane** [nemoware/analyser#76]
Для данного договора не определен контрагент и поэтому, вероятно, не нашелся протокол. (В документах протокол для этого договора есть).
Но ошибка здесь не в отсутствии протокола, а в том что не был определен первостепенный атрибут "Контрагент" -  это не есть нарушение :)

![image](https://user-images.githubusercontent.com/55797683/70996578-22668d80-20e4-11ea-9f35-25ddbb852d2c.png)

![image](https://user-images.githubusercontent.com/55797683/70996648-475b0080-20e4-11ea-914e-6ae37e51dc06.png)

**Comment by compartia** [comment]
всегда будет оставаться вероятность, что контрагент не найден.
как должна себя вести система в таком случае?

**Comment by compartia** [comment]
> Но ошибка здесь не в отсутствии протокола, а в том что не был определен первостепенный атрибут "Контрагент" - это не есть нарушение :)

@JaneLit в таком случае этот баг должен называться "не определен "Контрагент""
И еще огромная просьба указывать id дока, чтобы можно было вынуть его детали из базы (или URL страницы)

**Comment by LitJane** [comment]
@compartia my fault. Контрагент не "не определился", а определился неправильно.
Создан отдельный issue.
