### ISSUE TITLE
Неправильно определился контрагент

### ISSUE THREAD

**Issue by LitJane** [nemoware/analyser#77]
![image](https://user-images.githubusercontent.com/55797683/70999260-1d0c4180-20ea-11ea-9e40-ab3d42502557.png)

Ссылка на документ https://drive.google.com/drive/u/1/folders/1hXviwYQydMvOADk9tsPsXQdVfD2aYIGz

**Comment by compartia** [comment]
partially closed in Nemoware Analyser v1.4.2
(dev branch)

является ли 'Фонд' нормальной формой собственности?

**Comment by LitJane** [comment]
@compartia она может и не нормальная, но не нам судить, однако :))) 

Это форма некоммерческих организаций наряду с такими как - Автономная некоммерческая организация, Некоммерческое партнерство, Благотворительный фонд, Учреждение, Ассоциация или союз, Общественное объединение, Коллегия адвокатов, Адвокатское бюро, Потребительский кооператив, Религиозное объединение, Национально-культурная автономия

**Comment by compartia** [comment]
in dev branch
