### ISSUE TITLE
В протоколе не определился контрагент

### ISSUE THREAD

**Issue by LitJane** [nemoware/analyser#78]
Ссылка на документ: https://drive.google.com/drive/u/1/folders/1hXviwYQydMvOADk9tsPsXQdVfD2aYIGz

![image](https://user-images.githubusercontent.com/55797683/70999750-0b776980-20eb-11ea-8c52-87d868dc4cb4.png)

**Comment by compartia** [comment]
closed in v1.4.6, branch `dev`
