### ISSUE TITLE
Почему предмет определен как "Сделка"?

### ISSUE THREAD

**Issue by LitJane** [nemoware/analyser#85]
![image](https://user-images.githubusercontent.com/55797683/71087881-41315680-21ae-11ea-9f11-6ab7fff2c03e.png)
Ссылка на документ (Договор под номером 4): https://drive.google.com/drive/u/1/folders/1hXviwYQydMvOADk9tsPsXQdVfD2aYIGz

**Comment by compartia** [comment]
duplicates #18

**Comment by compartia** [comment]
@LitJane 
краткий, но исчерпывающий ответ:

<img width="933" alt="Capture d’écran 2019-12-18 à 20 57 43" src="https://user-images.githubusercontent.com/7677437/71088564-acdce900-21d9-11ea-8fca-666762b14835.png">

**Comment by LitJane** [comment]
@compartia а какой формулировкой в договоре можно увеличить это "маловато", если в договоре предмет: "...принять и оплатить следующий Объект имущества"?

**Comment by compartia** [comment]
> какой формулировкой в договоре

договор нельзя менять

**Comment by LitJane** [comment]
@compartia в смысле нельзя менять, поясни или прокомментируй мои действия? 
Я загружаю договор  который называется "ДОГОВОР КУПЛИ-ПРОДАЖИ ИМУЩЕСТВА", в котором предмет звучит как: "Продавец обязуется передать в собственность Покупателю, а Покупатель обязуется принять и оплатить следующий Объект имущества".
Вопрос: какая должна быть формулировка в договоре, чтобы предмет определился как **Сделка с имуществом** и, соответственно, потребовался протокол к нему? 
_Вопрос актуален конкретно к завтрашнему (а затем и финальному) показу._

**Comment by compartia** [comment]
> поясни или прокомментируй мои действия?

поясняю твои действия: ты пытаешься мне сообщить о давно известной мне проблеме, над которой я работаю уже год и особенно активно с момента появления последнего контрольного сета.

**Comment by SergeyShalaevsky** [comment]
Артем, Жанна, вы оба по-своему правы, это просто по щелчку пальцев пофиксить нельзя, но Жанна просит, чтобы ты ей посоветовал, что должно быть примерно написано в доке, чтобы система определила это как "сделка с недвижимостью"

**Comment by compartia** [comment]
@SergeyShalaevsky если бы я был не согласен с этим багом, я бы поставил стату Invalid + WontFix. Но это duplicate

**Comment by compartia** [comment]
@LitJane @SergeyShalaevsky 
Жанна, если хочешь помочь, то есть известный тебе контрольный csv с перечнем договоров и ожидаемых значений, в который можно вносить интересные тебе доки. Я валидирую analyser against that csv.
