### ISSUE TITLE
v1.4.10 Не выявлено нарушение (возможно). Продажа имущества слишком дешево

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#90]
в протоколе "цена НЕ НИЖЕ 59,7 мил"
в договоре она ниже -- "цена 59 мил" 

<img width="1438" alt="Capture d’écran 2019-12-19 à 14 40 16" src="https://user-images.githubusercontent.com/7677437/71150893-8ff1f580-226d-11ea-8811-10d2882dc513.png">
<img width="1433" alt="Capture d’écran 2019-12-19 à 14 39 58" src="https://user-images.githubusercontent.com/7677437/71150895-908a8c00-226d-11ea-83fe-683b1f07d9bb.png">

**Comment by SergeyShalaevsky** [comment]
вообще это баг, но тут проблема с договором, у него subject: Deal и не определен контрагент

**Comment by compartia** [comment]
> у него subject: Deal и не определен контрагент

так было раньше, да,
но по данным последнего analyser (refer https://github.com/nemoware/analyser/releases/tag/v1.4.10)
все лучше

<img width="1531" alt="Capture d’écran 2019-12-19 à 16 42 11" src="https://user-images.githubusercontent.com/7677437/71158313-abb1c780-227e-11ea-92e2-ff05c0c89a2f.png">

**Comment by compartia** [comment]
(кстати, _очень_ предлагаю в багрепортах в заголовке указывать версию модуля, как стало здесь)

**Comment by SergeyShalaevsky** [comment]
очень странно у меня вообще нет ни каких значений в этом протоколе на этой версии
![image](https://user-images.githubusercontent.com/51235093/71165949-c8400680-2262-11ea-8cec-d2753950b203.png)

**Comment by compartia** [comment]
кстати, у меня другой `checksum:7328975850778030265`
парсер `version:"1.1.15"`
сейчас буду уточнять

**Comment by compartia** [comment]
@SergeyShalaevsky 
убедись, пожалуйста, что ты используешь последнюю версию с ветви master

<img width="785" alt="Capture d’écran 2019-12-19 à 19 42 01" src="https://user-images.githubusercontent.com/7677437/71171200-2d621f00-2298-11ea-93c0-6110aee5c8da.png">


(на скриншоте версия 1.4.11 -- я поменял у себя только что для того, чтобы анализатор переанализировал)

и кстати,  у меня обнаружилась проблема с checksum -- она сейчас поменялась, а не должна бы

**Comment by SergeyShalaevsky** [comment]
![image](https://user-images.githubusercontent.com/51235093/71176214-668b9680-227a-11ea-8731-16d58d9e51fc.png)

**Comment by compartia** [comment]
@SergeyShalaevsky 
please open this https://github.com/nemoware/analyser/blob/master/notebooks/dev_Protocols.ipynb
in CoLab
and follow  the instructions
to debug

**Comment by SergeyShalaevsky** [comment]
хорошее предложение, но делать это я конечно же, не буду :)

**Comment by compartia** [comment]
скриншот:
<img width="1618" alt="Capture d’écran 2019-12-19 à 22 46 43" src="https://user-images.githubusercontent.com/7677437/71182818-c7829100-22b1-11ea-8562-67db3520aba1.png">  -- этот Colab Notebook берет правильную чистую версию из гитхаба.
Атрибуты находятся, в JSON они тоже есть.

**Comment by compartia** [comment]
<img width="700" alt="Capture d’écran 2019-12-19 à 22 55 33" src="https://user-images.githubusercontent.com/7677437/71183333-c736c580-22b2-11ea-9f0c-f9f21a8e8850.png">

**Comment by SergeyShalaevsky** [comment]
можно сколько угодно обводить кружочками версии, но код от этого кросс-платформенным не станет :(
